""" This is a "compiled" version containing only those dlls and functions that are actually used by the application """

from ctypes.wintypes import *
from .types import *

advapi32 = ctypes.windll.advapi32
comctl32 = ctypes.windll.comctl32
comdlg32 = ctypes.windll.comdlg32
gdi32 = ctypes.windll.gdi32
kernel32 = ctypes.windll.kernel32
ole32 = ctypes.windll.ole32
shell32 = ctypes.windll.shell32
user32 = ctypes.windll.user32

advapi32.RegCloseKey.argtypes = (HKEY,)
advapi32.RegCloseKey.restype = LSTATUS
advapi32.RegCreateKeyW.argtypes = (HKEY, LPCWSTR, PHKEY)
advapi32.RegCreateKeyW.restype = LSTATUS
advapi32.RegOpenKeyW.argtypes = (HKEY, LPCWSTR, PHKEY)
advapi32.RegOpenKeyW.restype = LSTATUS
advapi32.RegQueryValueExW.argtypes = (HKEY, LPCWSTR, LPDWORD, LPDWORD, LPVOID, LPDWORD)
advapi32.RegQueryValueExW.restype = LSTATUS
advapi32.RegSetValueExW.argtypes = (HKEY, LPCWSTR, DWORD, DWORD, LPVOID, DWORD)
advapi32.RegSetValueExW.restype = LSTATUS
comctl32.ImageList_LoadImageW.argtypes = (HINSTANCE, LPCWSTR, INT, INT, COLORREF, UINT, UINT)
comctl32.ImageList_LoadImageW.restype = HANDLE
comdlg32.GetOpenFileNameW.argtypes = (LPVOID,)
comdlg32.GetSaveFileNameW.argtypes = (LPVOID,)
gdi32.CreateFontW.argtypes = (INT, INT, INT, INT, INT, DWORD, DWORD, DWORD, DWORD, DWORD, DWORD, DWORD, DWORD, LPCWSTR)
gdi32.CreateFontW.restype = HFONT
gdi32.CreateSolidBrush.argtypes = (COLORREF,)
gdi32.CreateSolidBrush.restype = HBRUSH
gdi32.DeleteObject.argtypes = (HANDLE,)
gdi32.ExtTextOutW.argtypes = (HDC, INT, INT, UINT, LPRECT, LPCWSTR, UINT, LPINT)
gdi32.GetDeviceCaps.argtypes = (HDC, INT)
gdi32.GetStockObject.restype = HANDLE
gdi32.RoundRect.argtypes = (HDC, INT, INT, INT, INT, INT, INT)
gdi32.SelectObject.argtypes = (HDC, HANDLE)
gdi32.SelectObject.restype = HANDLE
gdi32.SetBkColor.argtypes = (HDC, COLORREF)
gdi32.SetBkMode.argtypes = (HDC, INT)
gdi32.SetDCBrushColor.argtypes = (HDC, COLORREF)
gdi32.SetTextColor.argtypes = (HDC, COLORREF)
kernel32.CloseHandle.argtypes = (HANDLE,)
kernel32.CreateEventW.argtypes = (INT, BOOL, BOOL, LPCWSTR)
kernel32.CreateEventW.restype = HANDLE
kernel32.GetModuleHandleW.argtypes = (LPCWSTR,)
kernel32.GetModuleHandleW.restype = HMODULE
kernel32.LoadLibraryW.restype = HANDLE
kernel32.SetEvent.argtypes = (HANDLE,)
kernel32.SetThreadExecutionState.argtypes = (UINT,)
kernel32.SetThreadExecutionState.restype = UINT
ole32.CoWaitForMultipleHandles.argtypes = (DWORD, DWORD, ULONG, LPHANDLE, LPDWORD)
shell32.DragFinish.argtypes = (WPARAM,)
shell32.DragQueryFileW.argtypes = (WPARAM, UINT, LPWSTR, UINT)
shell32.ShellExecuteW.argtypes = (HWND, LPCWSTR, LPCWSTR, LPCWSTR, LPCWSTR, INT)
shell32.ShellExecuteW.restype = HINSTANCE
shell32.Shell_NotifyIconW.argtypes = (DWORD, LPVOID)
user32.AppendMenuW.argtypes = (HWND, UINT, UINT_PTR, LPCWSTR)
user32.CheckMenuItem.argtypes = (HMENU, UINT, UINT)
user32.CreateWindowExW.argtypes = (DWORD, LPCWSTR, LPCWSTR, DWORD, INT, INT, INT, INT, HWND, HMENU, HINSTANCE, LPVOID)
user32.DefWindowProcW.argtypes = (HWND, UINT, WPARAM, LPARAM)
user32.DestroyWindow.argtypes = (HWND,)
user32.DialogBoxParamW.argtypes = (HINSTANCE, LPCWSTR, HWND, DLGPROC, LPARAM)
user32.DialogBoxParamW.restype = INT_PTR
user32.DispatchMessageW.argtypes = (LPMSG,)
user32.DrawTextW.argtypes = (HANDLE, LPCWSTR, INT, LPRECT, UINT)
user32.FillRect.argtypes = (HANDLE, LPRECT, HBRUSH)
user32.FindWindowExW.argtypes = (HWND, HWND, LPCWSTR, LPCWSTR)
user32.FindWindowExW.restype = HWND
user32.FindWindowW.argtypes = (LPCWSTR, LPCWSTR)
user32.FindWindowW.restype = HWND
user32.FrameRect.argtypes = (HDC, LPRECT, HBRUSH)
user32.GetClientRect.argtypes = (HWND, LPRECT)
user32.GetDC.argtypes = (HWND,)
user32.GetDC.restype = HDC
user32.GetDesktopWindow.restype = HWND
user32.GetDlgItem.argtypes = (HWND, INT)
user32.GetDlgItem.restype = HWND
user32.GetFocus.restype = HWND
user32.GetMenuBarInfo.argtypes = (HWND, LONG, LONG, LPVOID)
user32.GetMenuItemCount.argtypes = (HMENU,)
user32.GetMenuItemInfoW.argtypes = (HMENU, UINT, BOOL, LPVOID)
user32.GetMessageW.argtypes = (LPMSG,HWND,UINT,UINT)
user32.GetParent.argtypes = (HWND,)
user32.GetParent.restype = HWND
user32.GetWindowDC.argtypes = (HWND,)
user32.GetWindowDC.restype = HDC
user32.GetWindowLongPtrA.argtypes = (HWND, LONG_PTR)
user32.GetWindowLongPtrA.restype = ULONG
user32.GetWindowLongW.argtypes = (HWND, INT)
user32.GetWindowLongW.restype = LONG
user32.GetWindowRect.argtypes = (HWND, LPRECT)
user32.GetWindowTextW.argtypes = (HWND, LPWSTR, INT)
user32.InvalidateRect.argtypes = (HWND, LPRECT, BOOL)
user32.IsZoomed.argtypes = (HWND,)
user32.LoadAcceleratorsW.argtypes = (HINSTANCE, LPCWSTR)
user32.LoadAcceleratorsW.restype = HACCEL
user32.LoadCursorW.argtypes = (HINSTANCE, LPVOID)
user32.LoadIconW.argtypes = (HINSTANCE, LPCWSTR)
user32.LoadIconW.restype = HICON
user32.LoadImageW.argtypes = (HINSTANCE, LPCWSTR, UINT, INT, INT, UINT)
user32.LoadImageW.restype = HANDLE
user32.LoadMenuW.argtypes = (HINSTANCE, LPCWSTR)
user32.LoadMenuW.restype = HMENU
user32.MapWindowPoints.argtypes = (HWND, HWND, LPVOID, UINT)
user32.MessageBoxW.argtypes = (HWND, LPCWSTR, LPCWSTR, UINT)
user32.OffsetRect.argtypes = (LPRECT, INT, INT)
user32.RegisterWindowMessageW.argtypes = (LPCWSTR,)
user32.RegisterWindowMessageW.restype = UINT
user32.ReleaseDC.argtypes = (HWND, HANDLE)
user32.SendMessageW.argtypes = (HWND, UINT, LPVOID, LPVOID)
user32.SendMessageW.restype = LONG_PTR
user32.SetCapture.argtypes = (HWND,)
user32.SetClassLongPtrW.argtypes = (HWND, INT, LONG_PTR)
user32.SetLayeredWindowAttributes.argtypes = (HWND, COLORREF, BYTE, DWORD)
user32.SetMenu.argtypes = (HWND, HMENU)
user32.SetParent.argtypes = (HWND, HWND)
user32.SetWindowLongPtrA.argtypes = (HWND, LONG_PTR, ULONG)
user32.SetWindowLongPtrA.restype = LONG
user32.SetWindowLongPtrW.argtypes = (HWND, LONG_PTR, WNDPROC)
user32.SetWindowLongPtrW.restype = WNDPROC
user32.SetWindowPos.argtypes = (HWND, LONG_PTR, INT, INT, INT, INT, UINT)
user32.TrackPopupMenuEx.argtypes = (HANDLE, UINT, INT, INT, HANDLE, LPVOID)
user32.TranslateAcceleratorW.argtypes = (HWND, HACCEL, LPMSG)
user32.TranslateMessage.argtypes = (LPMSG,)
